[features]
seeds = false
skip-lint = false
[programs.localnet]
test = "Biw2CakNyp53dXgUMZBY9d3Fsd49pvP2KUc4wP817PBE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
